### ISSUE TITLE
Editar nombre del proyecto

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#1]
Desde la sección de setting renombren el proyecto empleando sus apellidos en lugar de sus nombres (al ser 3 cátedras, y es mucha gente, cuesta un poco encontrarlos por nombre)
![imagen](https://user-images.githubusercontent.com/8345007/166124370-bc70f0e8-7068-4cef-993d-2e2ec89fce0e.png)

**Comment by AntonioHuenz** [comment]
Listo profesora ya actualice el nombre y puse el apellido.
