### ISSUE TITLE
Error en la propiedad CSS

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#10]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/principal.css#L29

Debería ser:
`text-decoration: none;`

**Comment by AntonioHuenz** [comment]
listo profe , el archivo de css ya a sido actualizado.
