### ISSUE TITLE
Los ids de los elementos deben ser unívocos (no puede haber ids repetidos)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#11]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/datos.html#L16-L17

https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/carpeta_wireframe/Register/index.html#L15-L16

**Comment by AntonioHuenz** [comment]
esta parte del código ya lo hemos actualizado , gracias por la correccion.
