### ISSUE TITLE
Las etiquetas de títulos h1, h4 no deben estar contenidas dentro de una etiqueta p

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#12]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/Principal.html#L59-L66

**Comment by AntonioHuenz** [comment]
listo ya esta solucionado.
