### ISSUE TITLE
Todas las etiquetas deben estar escritas en minúsculas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#15]
Cambiar WIDTH y HEIGHT para que estén en minúscula.
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/pagfin.html#L37

**Comment by AntonioHuenz** [comment]
listo.
