### ISSUE TITLE
Falta atributo alt en TODAS las imágenes

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#16]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/pagfin.html#L30

https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/pagfin.html#L34

https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/pagfin.html#L37

https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/pagfin.html#L41

**Comment by AntonioHuenz** [comment]
Listo profe ya esta declarado las imagen
