### ISSUE TITLE
Algunos archivos no están correctamente indentados

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#19]
En Principal.html la indentación no es correcta, por ejemplo.
Asegurense siempre de seleccionar todo el código y en el menú hacer:

Code > Auto-Ident Lines

**Comment by AntonioHuenz** [comment]
listo profesora ya nos encargamos de la parte de navegación y las opciones fueron quitas por que eran para la segunda parte del proyecto donde si la contaremos y abra mas  navegación de página
