### ISSUE TITLE
Readme: Problemas con el título ### y ##

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#21]
Para que el texto "Autores" sea un título h3, debe dejarse un espacio en blanco entre "###" y "Autores"

Para que el texto "Tecnologías Usadas" sea un título h2, debe dejarse un espacio en blanco entre "##" y "Tecnologías Usadas"

**Comment by AntonioHuenz** [comment]
Listo.
