### ISSUE TITLE
No se pueden emplear estilos incrustados

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#27]
Los estilos deberían determinarse en una Hoja de estilo, y NO en el CSS
https://github.com/UCC-LabCompu2/Proyecto2022-Morales-Dalmasso/blob/96758441f0b0d49f4d7165132a16b050f805b60b/datos.html#L6-L14

**Comment by AntonioHuenz** [comment]
listo
