### ISSUE TITLE
CUIDADO con el nombre de los estilos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#3]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/estilo2_css.css#L1

**Comment by AntonioHuenz** [comment]
perdón profesora pero ese toro nos dio problemas y ya no sabias que ponerle por que no encontramos una solucion y bueno me canse y como ya estabamos cansado lo puteamos al toro XD pero ya lo cambio.
