### ISSUE TITLE
Identar adecuadamente todos los archivos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#34]
Identar correctamente:
- fultermis.css
- index.html
- jscv.html
- mineria.css
- mineria.html
- Toro.css

Recuerden que la mejor forma de identar es:
1) Realizar ctrol+A en un archivo para seleccionar (all) todo el contenido
2) En el menú de "Code" seleccionar "Reformat Code"
![imagen](https://user-images.githubusercontent.com/8345007/206871985-54474925-341b-46cd-9ca3-b3587d112ca6.png)

**Comment by bautidalmasso** [comment]
listo profe ya hicimos la identacion.
