### ISSUE TITLE
Nombre de carpeta incorrecta

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#35]
Dentro del proyecto no hay NINGUNA carpeta llamada "Wireframe". Corregir el nombre de la carpeta como corresponda.

https://github.com/UCC-LabCompu2/Proyecto2022-Morales-Dalmasso/blob/b6c707d32c6880c2879fac8dc21812e9ff506bd6/Toro.css#L8

Dentro del proyecto no hay NINGUNA carpeta llamada "Imagenes". Corregir el nombre de la carpeta como corresponda.
https://github.com/UCC-LabCompu2/Proyecto2022-Morales-Dalmasso/blob/b6c707d32c6880c2879fac8dc21812e9ff506bd6/datos.html#L9

**Comment by bautidalmasso** [comment]
se realizaron los cambios correspondientes
