### ISSUE TITLE
Nombre de etiqueta html incorrecta

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#36]
Si la etiqueta abierta es un `<p>`, entonces la etiqueta que se cierra debe ser `</p>`.

No existe la etiqueta `</Pid>`,

https://github.com/UCC-LabCompu2/Proyecto2022-Morales-Dalmasso/blob/b6c707d32c6880c2879fac8dc21812e9ff506bd6/mineria.html#L20

**Comment by bautidalmasso** [comment]
ya se arreglo
