### ISSUE TITLE
Agregar en la etiqueta <meta> la información de autores, descripción y palabras clave

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#39]
En el ```<head></head>``` incluir las etiquetas ```<meta>``` detallando: autor, descripcion y palabras clave

https://ucc-labcompu2.github.io/filminas/U4_HTML.html#/6

**Comment by bautidalmasso** [comment]
ya se agregaron en los tres HTML que tenemos en el proyecto
