### ISSUE TITLE
Nombre del archivo css con espacios

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#4]
Se recomienda que todos los archivos, textos, imagenes, css, html, NO CONTENGAN ESPACIOS, porque algunos navegadores pueden no encontrar los archivos.

Cambiar "inicio de datos.css" por "inicio_de_datos.css" o emplear camelCase "inicioDeDatos.css"

**Comment by AntonioHuenz** [comment]
listo :)
