### ISSUE TITLE
Falta etiqueta img

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#40]
Debe haber por lo menos una etiqueta ```<img>``` en la página.

Deberian cambiar para que todas las imágenes sean img en lugar de un div con contenido.
Es importante que esas imágenes tengan el atributo "alt" para la accesibilidad.

**Comment by bautidalmasso** [comment]
ya se agrego la etiqueta imagen <img> en el HTML
