### ISSUE TITLE
Error en nombre de input

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#41]
El "name" del input "password" debería ser "password". No tiene sentido semanticamente que diga "correo".
https://github.com/UCC-LabCompu2/Proyecto2022-Morales-Dalmasso/blob/b6c707d32c6880c2879fac8dc21812e9ff506bd6/datos.html#L18

**Comment by bautidalmasso** [comment]
ya se corrigió el nombre  en el name=password , ya se actualizo.
