### ISSUE TITLE
NO emplear estilos incrustados

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#5]
https://github.com/UCC-LabCompu2/proyecto2022-antonio-bauti/blob/e79f1735c40c13eea3e6a51a9dbf519e8bd5810d/Principal.html#L16-L44

En lugar de eso, se emplear los estilos en las hojas de estilo css.

**Comment by AntonioHuenz** [comment]
Listo
