### ISSUE TITLE
Recomendación: Unificar los estilos en un único CSS

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#6]
Teniendo en cuenta que la página web no es tan extensa, y que muchos estilos serán compartidos por los links, y otros elementos, se recomienda emplear un único CSS.

**Comment by AntonioHuenz** [comment]
Profe unifique casi todo los CSS en uno solo pero tuve un problema con el fondo de registro y bueno deje un CSS
