### ISSUE TITLE
Falta navegación entre páginas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2022-Morales-Dalmasso#9]
Hay muchos links o botones que no llevan a ningún lado.

**Comment by AntonioHuenz** [comment]
la parte de navegación entre paginas es por que esas la pusimos para completar la pagina para el segundo parcial pero en si lo mas necesario es Inicio-Registro-Perfil(que es lo que se muestra en la pagina final), las otras paginas ya fueron sacadas para que no haya confuciones.
